In [1]:
import pandas as pd
import numpy as np


In [4]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=10, n_classes=3, random_state=42, n_redundant=0, n_informative=3)

In [15]:
X, y

(array([[-0.36313165, -0.53005157,  0.07450959, ...,  1.37718094,
          1.02003651,  0.854402  ],
        [-0.03250389, -0.92677408, -0.53300408, ..., -0.86876754,
          0.61346017,  0.83049813],
        [ 0.16757011,  0.95796326, -1.63201489, ...,  0.61377086,
          0.37545586,  1.1622596 ],
        ...,
        [ 1.86404853,  0.19085762,  1.45482617, ..., -0.26592007,
          0.55687472, -2.14143088],
        [-0.33577862, -0.9985064 ,  1.3906436 , ...,  0.73395048,
         -0.57460186, -0.31710283],
        [ 0.8202324 , -1.59991726,  2.20201392, ...,  0.86254348,
         -1.69497344,  0.8173062 ]], shape=(1000, 10)),
 array([2, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 2, 0, 2, 1, 0, 0, 2, 2, 1, 2,
        2, 1, 0, 0, 1, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 2, 2,
        0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 1, 2, 2, 2, 0, 2, 0, 0,
        2, 2, 0, 1, 1, 2, 2, 2, 1, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 1, 1, 1,
        0, 1, 0, 2, 2, 1, 0, 2, 1, 1, 0, 2, 2, 1, 1, 2, 0, 

In [19]:
import seaborn as sns
sns.scatterplot(x=pd.DataFrame(X)[0], y=pd.DataFrame(X)[1], hue=y)

<Axes: xlabel='0', ylabel='1'>

In [6]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
#logistic regresion
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(multi_class='ovr')
logreg

LogisticRegression(multi_class='ovr')

In [9]:
logreg.fit(X_train, y_train)
logreg.score(X_test, y_test)

e:\CODING\Data Science\DataScience ML Scratch2025\DS from Scratch\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.655

In [11]:
y_pred = logreg.predict(X_test)
y_pred


array([2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 1, 2, 0, 0, 0, 0, 0, 2, 1, 1, 2, 0,
       0, 2, 2, 2, 0, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1, 1, 2, 0,
       1, 2, 2, 2, 2, 2, 0, 0, 1, 2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2,
       0, 0, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 0,
       2, 0, 1, 1, 2, 2, 2, 2, 2, 0, 1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0,
       2, 0, 2, 2, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2,
       2, 2, 0, 0, 0, 1, 2, 2, 0, 0, 2, 2, 1, 2, 1, 2, 2, 1, 0, 1, 0, 2,
       0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 2, 0,
       2, 2, 1, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [14]:
#check all score
from sklearn.metrics import classification_report, confusion_matrix

print("Score", logreg.score(X_test, y_test))
print("Classification report", classification_report(y_test, y_pred))
print("Confusion matrix", confusion_matrix(y_test, y_pred))



Score 0.655
Classification report               precision    recall  f1-score   support

           0       0.60      0.76      0.67        62
           1       0.55      0.35      0.43        62
           2       0.76      0.82      0.78        76

    accuracy                           0.66       200
   macro avg       0.64      0.64      0.63       200
weighted avg       0.64      0.66      0.64       200

Confusion matrix [[47  9  6]
 [26 22 14]
 [ 5  9 62]]
